import Nav from "@/app/_Components/Nav";
import ProtectedRoute from "@/app/_Components/ProtectedRoute";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={` ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProtectedRoute role="ADMIN">
          <main className="p-12">
            <h1 className="text-2xl font-bold">Admin Page</h1>
            {children}
          </main>
        </ProtectedRoute>
      </body>
    </html>
  );
}
