import Nav from "@/app/_Components/Nav";
import ProtectedRoute from "@/app/_Components/ProtectedRoute";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navLinks = [
    {
      name: "Home",
      url: "dashboard",
    },
    {
      name: "Set Grades",
      url: "dashboard/setGrades",
    },
    {
      name: "Set Schedules",
      url: "dashboard/setSchedules",
    },
  ];

  return (
    <html lang="en" className="scroll-smooth">
         <body
        className={` ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProtectedRoute role="TEACHER">
          <Nav navLinks={navLinks} showLogOut={true} />
          <main className="p-12">{children}</main>
        </ProtectedRoute>
      </body>
    </html>
  );
}
