import Nav from "@/app/_Components/Nav";
import ProtectedRoute from "@/app/_Components/ProtectedRoute";
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navLinks = [
    {
      name: "Home",
      url: "/teacher/dashboard",
    },
    {
      name: "Set Grades",
      url: "/teacher/dashboard/setGrades",
    },
    {
      name: "Set Schedules",
      url: "/teacher/dashboard/setSchedules",
    },
  ];

  return (
    <html lang="en" className="scroll-smooth">
         <body
        className={` ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProtectedRoute role="TEACHER">
        <SidebarProvider>
            <AppSidebar item={navLinks} />
            <main className="p-12 w-full">
              <SidebarTrigger />
              {children}
            </main>
          </SidebarProvider>
        </ProtectedRoute>
      </body>
    </html>
  );
}
